apiVersion: v2
name: oracle
type: application
version: 1.0.0
appVersion: "deb8d3650c809bf1e96c329ed421439967ab02de49fb6c5d748963ab8c159568"
description: Oracle daemon for Lido decentralized staking service
