apiVersion: v2
name: oracle
type: application
version: 1.0.0
appVersion: "0851cd003b4c9a13bd696dcb7892b3afa20e31f2d02ffd7e262cf6c1b874ad22"
description: Oracle daemon for Lido decentralized staking service
