apiVersion: v2
name: ejector
type: application
version: 1.0.0
appVersion: "6ea844fcb150c5c6222b37e1b7b35345a0d2e7c2c17e72baae7cf807a515544f"
description: Daemon service which loads LidoOracle events for validator exits and sends out exit messages when necessary.
