apiVersion: v2
name: ejector
type: application
version: 1.0.0
appVersion: "6d80a57895e0a4d577dc78b187d2bbc62742259ccc1efcadff16685bda7a817e"
description: Daemon service which loads LidoOracle events for validator exits and sends out exit messages when necessary.
