apiVersion: v2
name: council
type: application
version: 1.0.0
appVersion: "9cf75a504affb18bb45a2c214a024d7dcde8fada242ea5e0c9f51e6faaafe032"
description: The Lido Council Daemon monitors deposit contract keys and compares them to Lido's unused keys.
