name: Release and Upload Artifact

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - ./council
          - ./ejector
          - ./kapi
          - ./oracle
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          helm package . --version ${{ env.RELEASE_VERSION }}
          echo "$HELM_CREDENTIALS" | helm registry login -u _json_key --password-stdin https://europe-docker.pkg.dev
          ls
          helm push ${{ matrix.folder }}-${{ env.RELEASE_VERSION}}.tgz oci://europe-docker-docker.pkg.dev
        shell: bash
        env:
          HELM_CREDENTIALS: ${{ secrets.HELM_CREDENTIALS }}
